###
GET http://localhost:8080/api/courier/15

###


GET http://localhost:8080/api/courier

###

POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "model": {
    "createdDate": "2023-05-24T14:45:50.371043",
    "creatorID": 22,
    "firstName": "proba4",
    "lastName": "proba",
    "modifiedDate": "2023-05-24T14:45:50.371043",
    "modifiedID": 22,
    "phoneNumber": "+36706640672"
  }
}
###

DELETE http://localhost:8080/api/courier/15
###
PUT http://localhost:8080/api/courier/
Content-Type: application/json

{
  "model": {
    "createdDate": "2023-05-24T14:45:50.371043",
    "creatorID": 22,
    "firstName": "first_nameproba",
    "id": 308,
    "lastName": "last_name",
    "modifiedDate": "2023-05-24T14:45:50.371043",
    "modifiedID": 22,
    "phoneNumber": "+36706640672"
  }
}

