###
GET http://localhost:8080/api/food/11

###


GET http://localhost:8080/api/food/

###

POST http://localhost:8080/api/food
Content-Type: application/json

{
  "model": {
    "createdDate": "2023-05-24T15:45:50.371043",
    "creatorID": 22,
    "description": "leiras",
    "modifiedDate": "2023-05-24T15:45:50.371043",
    "modifiedID": 22,
    "name": "name",
    "price": 1232
  }
}
###

DELETE http://localhost:8080/api/food/2
###
PUT http://localhost:8080/api/food
Content-Type: application/json

{
  "model": {
    "id": 11,
    "createdDate": "2023-05-24T15:45:50.371043",
    "creatorID": 22,
    "description": "testleiras2",
    "modifiedDate": "2023-05-25T15:45:50.371043",
    "modifiedID": 22,
    "name": "name2",
    "price": 100
  }
}

