###
GET http://localhost:8080/api/order/33

###


GET http://localhost:8080/api/order/

###

POST http://localhost:8080/api/order/
Content-Type: application/json

{
  "model": {
    "createdDate": "2023-05-24T14:45:50.371043",
    "creatorID": 22,
    "modifiedDate": "2023-05-24T14:45:50.371043",
    "modifiedID": 22,
    "deliveryDate": "2023-05-24T14:45:50.371043",
    "courierID": 1,
    "settlement": "asd",
    "publicSpace": "asd",
    "publicSpaceNature": "asd",
    "houseNumber": 11,
    "foodList": [
      {
        "foodId": 10
      },
      {
        "foodId": 9
      }
    ]
  }
}
###

DELETE http://localhost:8080/api/order/30
###
PUT http://localhost:8080/api/order/
Content-Type: application/json

{
  "model": {
    "createdDate": "2023-05-24T14:45:50.371043",
    "creatorID": 22,
    "id": 31,
    "modifiedDate": "2024-05-24T14:45:50.371043",
    "modifiedID": 22,
    "deliveryDate": "2023-05-24T14:45:50.371043",
    "courierID": 15,
    "settlement": "asd",
    "publicSpace": "asd",
    "publicSpaceNature": "asd",
    "houseNumber": 11
  }
}

